# Generated by Django 4.0.4 on 2022-08-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learnapp', '0002_course_slug_alter_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
