# Generated by Django 4.0.4 on 2022-08-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learnapp', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
